# Generated by Django 4.2.13 on 2024-05-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
